-- VYNTRO platform quest pack v1
-- Attaches platform-owned quests to the existing VYNTRO project context.

with platform_quests as (
  select *
  from (
    values
      (
        'connect-wallet',
        'Connect your wallet',
        'Verify the wallet that will anchor swaps, DeFi reads, XP and future shard claims.',
        'wallet_connect',
        'onboarding',
        50,
        false,
        'wallet',
        'wallet_check',
        null,
        'integration_auto',
        'Connect wallet',
        '/profile/edit',
        0,
        'none'
      ),
      (
        'complete-profile',
        'Complete your profile',
        'Add the profile basics VYNTRO uses for reputation, rewards and visible standing.',
        'profile_complete',
        'onboarding',
        40,
        false,
        'none',
        'rule_auto',
        null,
        'rule_auto',
        'Edit profile',
        '/profile/edit',
        0,
        'none'
      ),
      (
        'join-vyntro-community',
        'Join VYNTRO community',
        'Join the VYNTRO project context so platform quests roll into one standing surface.',
        'community_join',
        'onboarding',
        35,
        false,
        'none',
        'rule_auto',
        null,
        'rule_auto',
        'Join community',
        '/communities/c0951cfd-b434-41d5-977d-813156934493',
        0,
        'none'
      ),
      (
        'first-safe-swap-review',
        'Review your first safe swap route',
        'Open VYNTRO Swap and review route, fee, slippage and custody notes before signing anything.',
        'swap_review',
        'lifetime',
        45,
        false,
        'none',
        'event_check',
        null,
        'integration_auto',
        'Review swap',
        '/defi/swap',
        0,
        'none'
      ),
      (
        'first-verified-swap',
        'Complete your first verified swap',
        'Confirm a non-custodial VYNTRO swap from your verified wallet.',
        'defi_swap',
        'lifetime',
        120,
        true,
        'tx_hash',
        'event_check',
        null,
        'integration_auto',
        'Open swap',
        '/defi/swap',
        25,
        'lifetime'
      ),
      (
        'daily-check-in',
        'Daily check-in',
        'Open your VYNTRO command surface and keep the daily XP loop alive.',
        'daily_check_in',
        'daily',
        20,
        false,
        'none',
        'event_check',
        null,
        'integration_auto',
        'Open home',
        '/home',
        0,
        'none'
      ),
      (
        'daily-real-action',
        'Complete a real daily action',
        'Complete one verified quest, raid, swap, DeFi claim or lootbox action today.',
        'daily_platform_action',
        'daily',
        35,
        false,
        'none',
        'event_check',
        null,
        'integration_auto',
        'Find action',
        '/quests',
        3,
        'daily'
      ),
      (
        'weekly-activity-streak',
        'Weekly activity streak',
        'Complete at least three real platform actions in the weekly window.',
        'weekly_activity_streak',
        'weekly',
        100,
        false,
        'none',
        'event_check',
        null,
        'integration_auto',
        'Build streak',
        '/xp',
        40,
        'weekly'
      ),
      (
        'verified-invite',
        'Invite an activated friend',
        'Invite a friend and earn only after they activate with a real VYNTRO action.',
        'referral',
        'weekly',
        60,
        false,
        'none',
        'event_check',
        null,
        'integration_auto',
        'Invite friend',
        '/profile/invites',
        20,
        'weekly'
      ),
      (
        'first-lootbox-open',
        'Open your first lootbox',
        'Spend shards on your first lootbox and record the milestone.',
        'lootbox_open',
        'lifetime',
        45,
        false,
        'none',
        'event_check',
        null,
        'integration_auto',
        'Open lootboxes',
        '/lootboxes',
        15,
        'lifetime'
      )
  ) as quest(
    slug,
    title,
    description,
    quest_type,
    cadence,
    project_points,
    proof_required,
    proof_type,
    verification_type,
    verification_provider,
    completion_mode,
    action_label,
    action_url,
    shard_reward_amount,
    shard_reward_window
  )
)
insert into public.quests (
  project_id,
  campaign_id,
  title,
  description,
  type,
  quest_type,
  status,
  xp,
  action_label,
  action_url,
  proof_required,
  proof_type,
  verification_type,
  verification_provider,
  verification_config,
  completion_mode,
  auto_approve
)
select
  'c0951cfd-b434-41d5-977d-813156934493'::uuid,
  null,
  platform_quests.title,
  platform_quests.description,
  platform_quests.quest_type,
  platform_quests.quest_type,
  'open',
  platform_quests.project_points,
  platform_quests.action_label,
  platform_quests.action_url,
  platform_quests.proof_required,
  platform_quests.proof_type,
  platform_quests.verification_type,
  platform_quests.verification_provider,
  jsonb_build_object(
    'source', 'vyntro_platform_quest',
    'platformQuestSlug', platform_quests.slug,
    'cadence', platform_quests.cadence,
    'shardRewardAmount', platform_quests.shard_reward_amount,
    'shardRewardWindow', platform_quests.shard_reward_window
  ),
  platform_quests.completion_mode,
  platform_quests.completion_mode in ('rule_auto', 'integration_auto')
from platform_quests
where not exists (
  select 1
  from public.quests existing
  where existing.project_id = 'c0951cfd-b434-41d5-977d-813156934493'::uuid
    and existing.verification_config ->> 'platformQuestSlug' = platform_quests.slug
);
